* 分层实验系统说明文档


- 域(domain) 是指流量的一个划分（一部分流量的意思）。
- 层(layer) 是指系统参数的一个子集。
- 实验(experiment) 是指在一个流量划分上，进行零个或多个参数的修改，并最后改变请
  求处理的过程。

实验参数可能并不相互独立（比如，粉色的字和粉色的背景）。有了这个限制，我们的
核心思路是将参数划分到N个子集。每个子集都关联着一个实验层，每个请求最多会被N个
实验处理（每层一个实验）。每个实验只能修改自己层相关联的参数（即在参数子集中的参
数），并且同一参数不能出现在多个层中。


发布层（Launch layers），发布层与前面介绍的实验层有下面区别：

- 发布层总是在默认域中（比如，它们有全部流量）。
- 发布层是对参数的一个独立划分，比如，一个参数最多只能同时在一个发布层和最多一个
  正常层中（一个域中）。
- 为了让发布层和正常层的重复参数配合起来。在发布层中的实验有着稍有不同的语法。特
  别是，在发布层的实验会为覆盖参数的默认值，作为新的默认值，换言之，如果没有正常
  实验层的实验覆盖了默认参数，那么在发布层的行为就像一个普通的实验，但如果实验层
  的实验覆盖了默认值，那么实验就会用这个覆盖的值，而不是系统的默认值，或是发布层
  实验中的参数值。


** 分配类型(diversion)

支持多种流量分配类型的主要目的一方面是为了保持处理的一致性，另外也希望可以覆盖到
所有可能的情况，比如因时间变化而表征出来的不同特征。基于这些原因，我们以特定的顺
序对不同的流量分配类型进行分流：用户id，cookie，cookie日期，随机。一旦这个请求被
某高优先级分配方式抽中后，其它低优先级的分配方式将忽略这个请求（图3），虽然这个顺
序最大化地了一致性，但它也有一个缺点，比如，在同一层中1%的cookie取模流量会比1%的
随机流量大，在极端情况下，我们会遇到流量饥饿问题。在实践中，一层之中一般只应有一
种分流类型，实验和对比实验必须使用相同的分流类型，最主要的影响是不同的分流类型实
验需要不同的样本量。

** 分配条件(condition)

如果一个请求先满足了流量分类顺序中的一个类型，它不会再考虑下面的分配类型，即使它
不满足这一种分配类型的分配条件(s)。这很重要，最好以一个例子来说明，如果我们通过特
定的cookie取模来得到实验的流量，我们将会得到一个无偏的分配。考虑一下一个指定
cookie取模上有两个实验，一个分配条件为日语流量，另一个分配条件是英语流量，而这个
cookie取模剩余的流量（即不是日语和英语的流量）将不会分配给以cookie分配方式的其它
实验，这是为了避免分配顺序后几种分配方式的偏置，重要的逻辑是不再将上述剩余的流量
分配给分配顺序后几种分配方式的实验了。我们通过将有偏的剩余流量分配一个偏置id来避
免偏置。
